<a href="https://colab.research.google.com/github/Sandymyatnoe/Sandymyatnoe/blob/main/00_python_fundamentals_video.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#OO.PyTorch Fundamentals

Resource notebook: https://github.com/deep-learning-with-pytorch/dlwpt-code

In [2]:
import torch
torch.__version__

'2.3.1+cu121'

In [3]:
#scalar

scalar=torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [6]:
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
matrix=torch.tensor([[7,8],
                     [9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
matrix.ndim

2

In [11]:
matrix.shape

torch.Size([2, 2])

In [12]:
matrix[1][0]

tensor(9)

In [13]:
tensor=torch.tensor([[[1,2,3],
                      [3,6,9],
                      [2,4,5]]])
tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [14]:
tensor.ndim

3

In [15]:
tensor.shape

torch.Size([1, 3, 3])

In [16]:
tensor[0][0][1]

tensor(2)

In [17]:
tensor1=torch.tensor([[[[1,2],[2,3],[4,5]],
                      [[0,1],[1,1],[2,2]]]])
tensor1

tensor([[[[1, 2],
          [2, 3],
          [4, 5]],

         [[0, 1],
          [1, 1],
          [2, 2]]]])

In [18]:
tensor1.shape

torch.Size([1, 2, 3, 2])

In [19]:
tensor1.ndim

4

In [20]:
#Random tensor


random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.8111, 0.3159, 0.4836, 0.3414],
        [0.5135, 0.6845, 0.7934, 0.9565],
        [0.1014, 0.8788, 0.4510, 0.9825]])

In [21]:
random_tensor.ndim

2

In [22]:
random_image_size_tensor=torch.rand(size=(3,224,224))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [23]:
#zeros and ones


zeros=torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [24]:
ones=torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [25]:
ones.dtype

torch.float32

In [26]:
random_tensor.dtype

torch.float32

In [27]:
#a range of tensor

one_to_ten= torch.arange(start=0,end=1000, step=77)
one_to_ten

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [28]:
ten_zeros=torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [29]:
ten_ones=torch.ones_like(input=one_to_ten)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [30]:
one_to_tw=torch.arange(1,21).reshape(2,2,5)
one_to_tw

tensor([[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]],

        [[11, 12, 13, 14, 15],
         [16, 17, 18, 19, 20]]])

In [31]:
#tensor datatype


float_32_tensor=torch.tensor([3.0,6.0,9.0],
                             dtype=None,
                             device='cpu',
                             requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [32]:
float_32_tensor.dtype

torch.float32

In [33]:
float_16_tensor=float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [34]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.])

In [35]:
int_32_tensor=torch.tensor([3,6,8], dtype=torch.long)
int_32_tensor

tensor([3, 6, 8])

In [36]:
float_32_tensor* int_32_tensor

tensor([ 9., 36., 72.])

In [37]:
#getting info form the tensor


some_tensor=torch.rand(3,4)
some_tensor

tensor([[0.0957, 0.6183, 0.3535, 0.9691],
        [0.2536, 0.5668, 0.5107, 0.1117],
        [0.7287, 0.2206, 0.0424, 0.5296]])

In [38]:
some_tensor.size(), some_tensor.dtype, some_tensor.device

(torch.Size([3, 4]), torch.float32, device(type='cpu'))

In [39]:
#manipulation tensors

tensor = torch.tensor([1,2,3])
tensor +10

tensor([11, 12, 13])

In [40]:
tensor-10

tensor([-9, -8, -7])

In [41]:
tensor*10

tensor([10, 20, 30])

In [42]:
tensor/10

tensor([0.1000, 0.2000, 0.3000])

In [43]:
#pytorch in-built function

torch.mul(tensor,10)

tensor([10, 20, 30])

In [44]:
torch.add(tensor,10)

tensor([11, 12, 13])

In [45]:
torch.subtract(tensor,10)

tensor([-9, -8, -7])

In [46]:
torch.divide(tensor,10)

tensor([0.1000, 0.2000, 0.3000])

In [47]:
tensor*tensor

tensor([1, 4, 9])

In [48]:
##matrix multiplication

torch.matmul(tensor, tensor)

tensor(14)

In [49]:
%%time
value=0
for i in range(len(tensor)):
  value+=tensor[i]*tensor[i]
print(value)


tensor(14)
CPU times: user 1.03 ms, sys: 1 ms, total: 2.03 ms
Wall time: 2.19 ms


In [50]:
%%time

torch.matmul(tensor, tensor)

CPU times: user 200 µs, sys: 0 ns, total: 200 µs
Wall time: 134 µs


tensor(14)

In [51]:
torch.matmul(torch.rand(3,2), torch.rand(2,4))

tensor([[0.4894, 0.1878, 0.4304, 0.7142],
        [0.5991, 0.2351, 0.4338, 0.8339],
        [0.5813, 0.2246, 0.4839, 0.8365]])

In [52]:
#shape for matrix multiplication

tensor_A=torch.tensor([[1,2],
                       [3,4],
                       [5,6]])
tensor_B=torch.tensor([[7,10],
                       [8,11],
                       [9,12]])

torch.mm(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [53]:
torch.mm(tensor_A.T, tensor_B)

tensor([[ 76, 103],
        [100, 136]])

In [54]:
#finding min, max,mean,sum,etc

x=torch.arange(0,100,10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [55]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [56]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [57]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [58]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [59]:
#finding the positional min and max

x.argmin()

tensor(0)

In [60]:
x.argmax()

tensor(9)

tensor(90)

In [68]:
#reshaping, stacking, squeezing and unsqueezing

import torch
x=torch.arange(1.,10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [87]:
x_reshaped=x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [88]:
z=x.view(9,1)
z, z.shape

(tensor([[5.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [89]:
z[0]=5
z,x

(tensor([[5.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [90]:

#stack

x_stacked=torch.stack([x,x,x,x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [91]:
x_hstackd=torch.hstack([x,x,x])
x_ystackd=torch.vstack([x,x,x])
x_hstackd, x_ystackd

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9., 5., 2., 3., 4., 5., 6., 7., 8., 9.,
         5., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.]]))

In [92]:
#squeeze. unsqueeze

x_reshaped, x_reshaped.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [94]:
x_squeezed= x_reshaped.squeeze()
x_squeezed, x_squeezed.shape

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [97]:
x_unsqueezed=x_squeezed.unsqueeze(dim=0)
x_unsqueezed, x_unsqueezed.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [99]:
#permute

x_original=torch.rand(size=(224,224,3))
x_permuted=x_original.permute(2,0,1)
x_original.shape, x_permuted.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

In [101]:
x_original[0,0,0]=15000

x_original[0,0,0], x_permuted[0,0,0]


(tensor(15000.), tensor(15000.))

In [102]:
#indexing

x=torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [105]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [107]:
x[0][0]

tensor([1, 2, 3])

In [110]:
x[0][2][2]

tensor(9)

In [111]:
x[:,0]

tensor([[1, 2, 3]])

In [114]:
x[:,:,1]

tensor([[2, 5, 8]])

In [115]:
x[:,1,1]

tensor([5])

In [117]:
x[0,0,:]

tensor([1, 2, 3])

In [118]:
x, x[0,:,2]

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 tensor([3, 6, 9]))

In [119]:
x[0][2][2]

tensor(9)

In [128]:
#pytorch tensor and numpy

#numpy to tensor

import torch
import numpy as np

array=np.arange(1.0,8.0)
tensor=torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [129]:
array.dtype, tensor.dtype

(dtype('float64'), torch.float64)

In [130]:
torch.arange(1.0,8.0).dtype

torch.float32

In [131]:
array=array+1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [132]:
#tensor to numpy

tensor=torch.ones(7)
numpy_tensor=tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [133]:
tensor.dtype, numpy_tensor.dtype

(torch.float32, dtype('float32'))

In [134]:
tensor=tensor+1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [140]:
#reproducbility
rand_A=torch.rand(3,4)
rand_B=torch.rand(3,4)
rand_A, rand_B

(tensor([[0.2122, 0.7254, 0.4541, 0.5524],
         [0.5940, 0.5285, 0.5501, 0.8719],
         [0.3132, 0.0730, 0.1180, 0.3899]]),
 tensor([[0.1316, 0.5569, 0.3732, 0.6689],
         [0.1464, 0.6792, 0.2647, 0.3452],
         [0.2527, 0.8385, 0.6059, 0.4724]]))

In [143]:
rand_A==rand_B

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [154]:
import torch

RANDOM_SEED=42
torch.manual_seed(RANDOM_SEED)
rand_C=torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
rand_D=torch.rand(3,4)
rand_C, rand_D

(tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]))

In [155]:
rand_C==rand_D

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [2]:
#running tensors and pytorch objects on the GPU

!nvidia-smi

Wed Jul 31 05:11:16 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   41C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [3]:
#check for GpU access with pytorch

import torch
torch.cuda.is_available()

True

In [5]:
#setup device agnostic code

device="cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [6]:
#count number of device

torch.cuda.device_count()

1

In [8]:
#putting tensors (and models) on the GPU

#on cpu

tensor=torch.tensor([1,2,3])
tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [9]:
#move to GPU

tensor_on_gpu=tensor.to(device)
tensor_on_gpu



tensor([1, 2, 3], device='cuda:0')

In [12]:
#moving back to cpu

#tensor_on_gpu.numpy()

tensor_back_cpu=tensor_on_gpu.cpu().numpy()
tensor_back_cpu

array([1, 2, 3])

In [13]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')